# Generated by Django 4.1.7 on 2023-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default='2021-12-12'),
        ),
    ]
